name: Build 25.12.x QEMU-armsr-armv8
# 你可以理解为这是一种 ARM64 平台下通用型 OpenWrt ,产出格式为 qcow2,适合所有 ARM64 平台的虚拟机
# 比如斐讯 N1 刷了 armbian 系统，armbian 系统里安装了 PVE 虚拟机 可用
# 比如新款 Apple Silicon 芯片的苹果电脑里的虚拟机 UTM 可用
# 比如友善 NanoPi R3S、R5S 官方推出的预装了 PVE 的 debian 系统 可用
# 比如瑞莎 E20C 刷了 Armbian 系统，自己安装了 QEMU+KVM 虚拟机 可用
on:
  workflow_dispatch:
    inputs:
      luci_version:
        description: "选择 luci 版本"
        required: false
        default: "25.12.1"
        type: choice
        options:
          - 25.12.0-rc1
          - 25.12.0-rc2
          - 25.12.0
          - 25.12.1
      profile:
        type: choice
        description: |
          可用于 ARM64 虚拟机 (比如 macOS 下的 UTM 虚拟机 比如斐讯 N1/R3S/R5S 等 arm64 系统的 PVE 虚拟机)
        options:
          - generic
        required: true
        default: 'generic'
      rootfs_partsize:
        description: '设置软件包大小 单位 (MB) 最大数值 10240'
        required: true
        default: '2048'
      enable_store:
        description: "集成 store 商店"
        required: false
        type: boolean
        default: true
      enable_pppoe:
        description: "是否配置 PPPoE 拨号信息？"
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'
      pppoe_account:
        description: "宽带账号 (若启用 PPPoE)"
        required: false
      pppoe_password:
        description: "宽带密码 (若启用 PPPoE)"
        required: false
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/armsr-armv8/build.sh

      - name: Enable Store integration
        run: |
          if [ "${{ github.event.inputs.enable_store }}" == "true" ]; then
            echo 'CUSTOM_PACKAGES="$CUSTOM_PACKAGES luci-app-store"' >> shell/apk-custom-packages.sh
            echo "✅ 已追加 luci-app-store"
          else
            echo "❎ 未启用 luci-app-store"
          fi

      - name: Validate PPPoE Inputs
        run: |
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
              exit 1
            fi
          fi

      - name: Building armsr-armv8 QEMU ImmortalWrt 25.12.x
        run: |
          profiles="${{ github.event.inputs.profile }}"
          rootfs_partsize="${{ github.event.inputs.rootfs_partsize }}"
          luci_version="${{ github.event.inputs.luci_version }}"

          IFS=',' read -r -a profile_array <<< "$profiles"

          for profile in "${profile_array[@]}"; do
            echo "Building for profile: $profile"

            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
              -v "${{ github.workspace }}/files/etc/uci-defaults:/home/build/immortalwrt/files/etc/uci-defaults" \
              -v "${{ github.workspace }}/arch/arch.conf:/home/build/immortalwrt/files/etc/opkg/arch.conf" \
              -v "${{ github.workspace }}/armsr-armv8/imm.config:/home/build/immortalwrt/.config" \
              -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
              -v "${{ github.workspace }}/armsr-armv8/build.sh:/home/build/immortalwrt/build.sh" \
              -e PROFILE="$profile" \
              -e ROOTFS_PARTSIZE="$rootfs_partsize" \
              -e ENABLE_PPPOE="${{ inputs.enable_pppoe }}" \
              -e PPPOE_ACCOUNT="${{ inputs.pppoe_account }}" \
              -e PPPOE_PASSWORD="${{ inputs.pppoe_password }}" \
              immortalwrt/imagebuilder:armsr-armv8-openwrt-${luci_version} /bin/bash -c "mkdir -p /home/build/immortalwrt/scripts && touch /home/build/immortalwrt/scripts/opkg-key && chmod +x /home/build/immortalwrt/scripts/opkg-key && echo 'CONFIG_USE_APK=y' >> /home/build/immortalwrt/.config && sed -i '/block-readers\|small-readers/d' /home/build/immortalwrt/include/image.mk && /home/build/immortalwrt/build.sh"
          done
      - name: Copy Firmware to workspace
        run: |
          cp ${{ github.workspace }}/bin/targets/armsr/armv8/*.qcow2 ${{ github.workspace }}
          cp ${{ github.workspace }}/bin/targets/armsr/armv8/*.vmdk ${{ github.workspace }}
      - name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: QEMU
          name: ImmortWrt-QEMU-armsr-armv8-25.12.x
          body_path: ${{ github.workspace }}/armsr-armv8/info.md
          files: |
            ${{ github.workspace }}/*.qcow2
            ${{ github.workspace }}/*.vmdk
          token: ${{ secrets.GITHUB_TOKEN }}
